### PR TITLE
Small changes to readme

### PR DESCRIPTION
**Pull request by KAMiKAZOW**

### CODE REVIEW

**Comment by jafrewa** [comment]
Isnt this broken ?

**Comment by KAMiKAZOW** [comment]
Nothing is broken about my PR. In the English language there are no spaces before punctuation. That's it.

**Comment by jafrewa** [comment]
I was talking about JodelPy as a whole

**Comment by KAMiKAZOW** [comment]
Don't know. Didn't have the chance, yet, to work with it (it's on my todo). I just encountered a few typos and I fixed them. That's all. ;)

**Comment by jafrewa** [comment]
Anyways thanks for contributing.

**Comment by ppati000** [comment]
Hey guys :)
I didn't try it, but posting should almost certainly be broken because of HMAC authorization.

**Comment by jafrewa** [comment]
Thanks for tuning in! Any hints on how to fix that?

**Comment by ppati000** [comment]
Not really, you'd need to have a private key for that... If you are planning to do a specific project (like the Wodel guy), you could try asking the Jodel team for help.

**Pull request merged**
